# -*- coding: utf-8 -*-
"""SANDIV'S Python lesson 1 work 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1a2vHOyAzo2ZClskvQKczyE8r1bD4CctY
"""

i = "THIS IS "
t = "Python "
g = "3.10"
n = i + t + g
print(n)
print("       ")

s = "HI I AM "
d = "SANDIV ."
j = s + d
print(j)
print("       ")

print("ID")
print("       ")

O = "Username = ICE_KING"
U = 'SANDIV'
y = 2610
z = 1.026

print(O)
print(id(O))
print("       ")

print(U)
print(id(U))
print("       ")

print(y)
print(id(y))
print("       ")

print(z)
print(id(z))
print("       ")

print("ID INFORMATION ENDS HERE.")
print("       ")

print("Addition")
print("10+25 =")
print("Answer is....")
a = 10
b = 25
z = a + b
print(z)
print("       ")

print("Subtraction")
print("15-5 =")
print("Answer is....")
p = 15
r = 5
h = p - r
print(h)
print("       ")

l = "All "
k = "this "
m = "from "
n = "the "
z = "lesson ."
print(l + k + m + n + z)
print("       ")

print("       ")
x = ("apple") #<you can change this ("apple") part, the one you want to print.
print(x)
print(type(x))
print("identifier ^ ")